language: go

sudo: required

go:
  - "1.13"

dist: trusty

env:
  global:
  # - GO111MODULE=on # enable Golang modules

before_script:
  - go get -v ./...

script:
  - make test
  - make build

after_success:
  #  report code cover
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN